name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Setup yq
      run: |
        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        chmod +x /usr/local/bin/yq

    - name: Validate Makefile syntax
      run: |
        make help
        make init

    - name: Validate example chart configurations
      run: |
        echo "Validating chart source configurations..."
        for config in sources/*.yaml; do
          echo "Checking $config..."
          if [ -f "$config" ]; then
            # Basic YAML validation
            yq eval '.' "$config" > /dev/null
            echo "✓ $config is valid YAML"
          fi
        done

    - name: Test chart processing (dry run)
      run: |
        echo "Testing chart processing with example charts..."
        # Create a temporary test environment
        mkdir -p test-charts
        cp -r sources/* test-charts/
        
        # Test that the Makefile targets work without actually downloading
        echo "Testing make targets..."
        make help
        make init
        
        echo "✓ All tests passed"
